baseURL = "https://banethero.github.io"
languageCode = "en-us"
title = "Ben & Janet Collection"  
defaultContentLanguage = "en"
disableKinds = ["taxonomy", "term", "RSS", "sitemap"]
timeZone = "America/Chicago"
theme = "github.com/nicokaiser/hugo-theme-gallery/v2"
publishDir = "docs"
enableRobotsTXT = true
googleAnalytics = "G-X1ZRN8D0BN"

[params]
  defaultTheme = "dark"

[outputs]
  page = ["HTML"]
  home = ["HTML"]
  section = ["HTML"]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.121.1"

[imaging]
  #resampleFilter = "CatmullRom"
  quality = 90
  [imaging.exif]
    AutoOrient = true
    #disableDate = false
    #disableLatLong = true
    #includeFields = "ImageDescription"