baseURL = 'https://banethero.github.io'
languageCode = 'en-us'
title = 'Ben & Janet Collection'
defaultContentLanguage = "en"

theme = ["github.com/nicokaiser/hugo-theme-gallery/v2"]

[params]
  defaultTheme = "dark"

[outputs]
  page = ["HTML"]
  home = ["HTML"]
  section = ["HTML"]

[imaging]
  resampleFilter = "CatmullRom"
  quality = 75
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription"