baseURL = 'https://banethero.github.io'
languageCode = 'en-us'
title = 'Ben & Janet Collection'
defaultContentLanguage = "en"

theme = ["github.com/nicokaiser/hugo-theme-gallery/v2"]

[params]
  defaultTheme = "dark"

[outputs]
  page = ["HTML"]
  home = ["HTML"]
  section = ["HTML"]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.112.0"